# tcp listen address
listenAddress: 0.0.0.0:1111
# store settings
store:
  # store type
  type: database
  # store-specific parameters
  params:
    # sql driver
    driverName: postgres
    # sql connection string
    dsn: postgres://admin:admin@localhost/proxy?sslmode=disable
    # specific user column
    userColumn: username
    # specific queries
    queries:
      # specific add user sql query
      addUserExecQuery: "INSERT INTO users (\"username\", \"password\") VALUES (:user,:password)"
      # specific search user sql query
      getUserQuery: "SELECT password FROM users WHERE \"username\" = :user"

# settings for password hashing
password:
  # hashing algorithm (sha and bcrypt now supported)
  type: bcrypt
  params:
    cost: 20